# Generated by Django 2.0.4 on 2018-07-24 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_data',
            name='games_played',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_data',
            name='games_won',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
